# version: "3"
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     environment:
#       - OLLAMA_HOST=http://127.0.0.1:11434
#     volumes:
#       - ./app:/app
#     depends_on:
#       - db
#     restart_policy:
#       condition: on-failure

#   db:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=secret
#       - POSTGRES_DB=fastapi
#       - POSTGRES_USER=fastapi
#       - POSTGRES_HOST_AUTH=md5
